name: a workflow to check for broken links in the MA website every 10 mins
on:
  schedule:
    - cron: '30 * * * *'

env:
  URL: https://micro-acquisition.alpha.canada.ca

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Link Snitch
        id: broke
        uses: victoriadrake/link-snitch@v1.0.0
        run: echo ::set-output name=broken::value
      - if: steps.broke.outputs.broken == 0
        name: Create an issue
        uses: JasonEtco/create-an-issue@v2.4.0
